CREATE SCHEMA  if not exists DBPERSON;

use DBPERSON;

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE TB_PERSON;
SET FOREIGN_KEY_CHECKS=1;

-- Person
insert into TB_OPERATOR (ID_OPERATOR, NAME,LOGIN,PASSWORD,PERFIL,DT_REGISTER,ADMIN) values (1 , 'ADMINISTRADOR', 'paulo', '$2a$10$j9nUcTBA.73RdvRfmpH6Yu2m3RbXczoHS4AtiHqm/74kH9tZn3Zey', 'GESTOR',sysdate,1);

--Person 2
insert into TB_OPERATOR (ID_OPERATOR, NAME,LOGIN,PASSWORD,PERFIL,DT_REGISTER,ADMIN) values (2 , 'GESTOR', 'paulol', '$2a$10$dDea8j1BRPBy3e4WZ3gjYucRk7aCpoK7ZjJOYKa1Mqc/leRRW62uK', 'GESTOR',sysdate,0);
