CREATE TABLE IF NOT EXISTS  TB_OPERATOR
(
    ID_OPERATOR   BIGINT UNSIGNED AUTO_INCREMENT,
    NAME          VARCHAR (100) NOT NULL,
    LOGIN         VARCHAR(15) NOT NULL,
    PASSWORD      VARCHAR(15) NOT NULL,
    PERFIL        VARCHAR(20) NOT NULL,
    DT_REGISTER   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADMIN         NUMBER (1) NOT NULL,
    PRIMARY KEY (ID_OPERATOR)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;