create table IF NOT EXISTS TB_PHONE
(
    ID_PHONE  BIGINT  UNSIGNED AUTO_INCREMENT,
    ID_PERSON   BIGINT UNSIGNED,
    NUMBER      VARCHAR(12) NOT NULL,
    COD_AREA     bigint NOT NULL,
    PHONE_TYPE  VARCHAR(20) NOT NULL,
    DT_REGISTER  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OPERATOR_LOGIN VARCHAR (40) NOT NULL ,
    CONSTRAINT `FK_PERSON_PHONE` FOREIGN KEY (ID_PERSON) REFERENCES TB_PERSON (ID_PERSON) ON DELETE CASCADE,
    PRIMARY KEY (ID_PHONE)
) engine = INNODB
  default charset = utf8;